baseURL: https://blog.fecodoo.ml/
publishDir: ./public/
languageCode: en-us
title: Yao Kai
paginate: 5
theme: hyde

Menus:
  main:
    - Name: "Github"
      URL: "https://github.com/fecodoo/"
    - Name: "Telegram"
      URL: "https://t.me/fecodoo"
    - Name: "LinkedIn"
      URL: "https://www.linkedin.com/in/凯-姚-211242187"
      
params:
  # description: "If nothing is impossible, one knows no limits.\tIf one knows no limits, one may rule the empire."
  description: "无不克则莫知其极，莫知其极，可以有国"

  themeColor: "theme-base-08"